name: Build CPS for Dev
concurrency: ${{ github.repository }}-database-migration-${{ github.ref_name }}

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      
      - name: Check out code
        uses: actions/checkout@v3

      - name: Display current directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Zip files
        run: |
          mkdir temp
          mv components/layouts/post-grid.tsx temp
          mv components/post-list temp
          zip -r myzip.zip temp
      - name: Verify zipped content
        run: |
          unzip -l myzip.zip


